name: Generate Snake 🐍

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
      - name: Generate snake animation files
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: aadi-aarrllo  # Make sure your GitHub username is correct
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/github-contribution-grid-snake.svg  # To generate the normal one as well if needed
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.2.0
        with:
          target_branch: output
          build_dir: dist
          commit_message: "🐍 Updated dark mode snake animations with latest contributions!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
